version: '{build}'
os: Visual Studio 2019
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
  Cap_MySql_ConnectionStringTemplate: Server=localhost;Database={0};Uid=root;Pwd=Password12!;Allow User Variables=True;SslMode=none
services:
  - mysql
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: Qjj0e1B9giVIpozI/J3DMcF5nT1hchlE3xpGctBoqMrT8r/0Z1suwEdMAfTBMkjn
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
