version: '{build}'
os: Visual Studio 2015
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
  Cap_SqlServer_ConnectionStringTemplate: Server=(local)\SQL2014;Database={0};User ID=sa;Password=Password12!
services:
  - mssql2014
build_script:
- ps: ./ConfigureMSDTC.ps1
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: /gak8VxtAbZvOTqON513KwsK5BtDUmoPjjzCMu+tn2i+vkupZbjnIKq/XnP4GGgv
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
