version: '{build}'
os: Visual Studio 2017
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
  Cap_SqlServer_ConnectionStringTemplate: Server=(local)\SQL2014;Database={0};User ID=sa;Password=Password12!
  Cap_MySql_ConnectionStringTemplate: Server=localhost;Database={0};Uid=root;Pwd=Password12!;Allow User Variables=True
  Cap_PostgreSql_ConnectionStringTemplate: Server=localhost;Database={0};UserId=postgres;Password=Password12!
services:
  - mssql2014
  - mysql
  - postgresql
  - mongodb
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: jzEiNdfiHYkpKBFoxtV+Tu48pJxBpPpu4CnQRsGnhu0Sx59sXgKVgfcg759sSWAO
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
