# Project information
site_name: CAP
site_url: https://cap.dotnet-chain.com
site_description: Project documentation with Markdown.
site_author: CAP Team
repo_name: 'dotnetcore/CAP'
repo_url: 'https://github.com/dotnetcore/cap'

# Copyright
copyright: Copyright &copy; 2017 <a href="https://github.com/dotnetcore">.NET Core Community</a>, Maintained by the <a href="/about/contact-us/#cap-team">CAP Team</a>.

nav:
    - Home: index.md
    - User Guide:
        - Getting Started: user-guide/getting-started.md
        - API Interface: user-guide/api-interface.md
        - Configuration: user-guide/configuration.md
        - Design Principle: user-guide/design.md
        - Implementation Mechanisms: user-guide/implementation.md
        - Distributed Transactions: user-guide/transaction.md
        - FAQ: user-guide/faq.md
    - 使用指南:
        - 快速开始: user-guide-cn/getting-started.md
        - API 接口: user-guide-cn/api-interface.md
        - 配置: user-guide-cn/configuration.md
        - 设计原理: user-guide-cn/design-principle.md
        - 实现: user-guide-cn/implementation-mechanisms.md
        - 分布式事务: user-guide-cn/distributed-transactions.md
        - FAQ: user-guide-cn/faq.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - Contact Us: about/contact-us.md

#theme: material
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'indigo'  
  language: 'en'
  #logo: 'img/logo.png'
  #favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

#Customization
extra:
  manifest: 'manifest.webmanifest'
  disqus: 'cap-1'
  social:
    - type: 'github'
      link: 'https://github.com/dotnetcore/cap'
    - type: 'twitter'
      link: 'https://twitter.com/ncc_community'
    - type: 'weibo'
      link: 'https://weibo.com/dotnetcore'
#   search:
#     language: 'en, zh'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dotnetcore
      repo: cap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde